name: Umbrella NB1 Android Kernel CI

on: [push]

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list
        apt-get -y update
        apt-get -y install build-essential fakeroot rsync git wget python3-debian dpkg-sig lz4 sbsigntool curl

    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: Setup Environment Variables
      run: |
        export ARCH="arm64"
        export SUBARCH="arm64"
        TRIPLET=$(basename $(pwd)/toolchain/bin/*gcc | sed 's|gcc$||g')
        export CROSS_COMPILE="$(pwd)/toolchain/bin/$TRIPLET"
        export KBUILD_OUTPUT="$(pwd)/out"
        export KBUILD_BUILD_USER="user"
        export KBUILD_BUILD_HOST="build"
        $(pwd)/toolchain/bin/${TRIPLET}gcc --version

    - name: make clean
      run: make clean

    - name: make mrproper
      run: make mrproper

    - name: make defconfig
      run: make nb1_defconfig

    - name: make
      run: make -j4 LOCALVERSION=-$(date +'%Y-%m-%d')

    - name: Package kernel image
      run: umbrella/package.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: umbrella-latest
        path: release
